- name: Run api tests
  hosts: localhost
  tasks:
    - name: Pull test image
      community.docker.docker_image:
        name: "localhost:5005/{{ image_name }}"
        tag: "{{ version }}"
        source: pull

    - name: Get current workdir
      ansible.builtin.command: pwd
      register: pwd_result

    - name: Allure results exist
      ansible.builtin.file:
        path: "{{ pwd_result.stdout }}/allure-results"
        state: directory
        mode: '0755'

    - name: Junit results exist
      ansible.builtin.file:
        path: "{{ pwd_result.stdout }}/surefire-reports"
        state: directory
        mode: '0755'

    - name: Run tests
      ignore_errors: true
      community.docker.docker_container:
        name: "{{ image_name }}-tests"
        image: "localhost:5005/{{ image_name }}:{{ version }}"
        state: started
        network_mode: host
        command: "{{ mvn_args | trim if mvn_args | default('') | trim | length > 0 else omit }}"
        mounts:
          - type: bind
            source: "/var/run/docker.sock"
            target: "/var/run/docker.sock"
          - type: bind
            source: "/etc/jenkins/jenkins_home/workspace{{ pwd_result.stdout }}/allure-results"
            target: "/allure/target/allure-results"
          - type: bind
            source: "/etc/jenkins/jenkins_home/workspace{{ pwd_result.stdout }}/surefire-reports"
            target: "/allure/target/surefire-reports"
        detach: false