- name: Run api tests
  hosts: localhost
  tasks:
    - name: Pull test image
      community.docker.docker_image:
        name: "localhost:5005/{{ branch }}"
        tag: latest
        source: pull

    - name: Run tests
      community.docker.docker_container:
        name: "{{ branch }}-tests"
        image: "localhost:5005/{{ branch }}:latest"
        detach: false
        cleanup: true
      register: result

    - name: Remove container
      community.docker.docker_container:
        name: "{{ branch }}-tests"
        state: absent
      when: result is defined

    - name: Check test results
      fail:
        msg: "Tests failed with exit code {{ result.container.State.ExitCode }}"
      when: result.container.State.ExitCode != 0